name: Update Coalition Data

on:
  schedule:
    - cron: "0 5 * * 1"  # Montags um 6:00 Uhr MEZ
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.24.3  # Explizite Installation
          pip install -r requirements.txt

      - name: Run Scraper
        run: |
          # Aktiviert die UTF-8 Unterstützung
          PYTHONIOENCODING=utf-8
          python scraper.py
          cat data.json  # Debug-Ausgabe

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Update coalition data" || echo "No changes to commit"
          git push
