name: Update Coalition Data

on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run Scraper and Generate Data
        run: |
          python scraper.py
          cat data.json

      - name: Commit Changes to Repository
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data.json scraper.log || true
          git commit -m "Update data $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push || echo "No changes to push"
