# .github/workflows/update-coalitions.yml
name: Update Coalition Data

on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10  # Explizite Python 3.10 Installation
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          check-latest: true

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run Scraper
        run: |
          python -X utf8 scraper.py
          cat data.json

      - name: Commit Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data.json
          git commit -m "Update data $(date +'%Y-%m-%d')" || echo "No changes"
          git push
